services:
  mongo:
    image: mongo:latest
    container_name: mongo-container
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 123123
    volumes:
      - mongo_data:/data/db
    networks:
      - micronaut

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express-container
    depends_on:
      - mongo
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123123
      ME_CONFIG_BASICAUTH_USERNAME: myuser
      ME_CONFIG_BASICAUTH_PASSWORD: 123123
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_URL: mongodb://admin:123123@localhost:27017/micronaut?authSource=admin
    networks:
      - micronaut

volumes:
  mongo_data:

networks:
  micronaut:
    driver: bridge